mybatis-plus:
  mapper-locations: classpath*:com/wong/**/xml/*Mapper.xml
  global-config:
    id-type: 0
    db-column-underline: false
    refresh-mapper: true

spring:
  datasource:
    url: jdbc:mysql://129.204.81.136:3306/mooc_meetingfilm?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: root
    password: wong0918
    filters: log4j,wall,mergeStat


logging:
  config: classpath:logback.xml
